"""Database handler for settings table.

Stores application settings with key-value structure supporting multiple value types.
"""

from __future__ import annotations

import logging
from typing import Any, List

import pymysql

from .....db_models.admin_models import SettingRecord
from ....config import DbConfig
from ....shared.core.db_driver import Database

logger = logging.getLogger(__name__)


class SettingsDB:
    """MySQL-backed application settings store."""

    def __init__(self, database_data: DbConfig):
        self.db = Database(database_data)

    def _row_to_record(self, row: dict[str, Any]) -> SettingRecord:
        return SettingRecord(**row)

    def fetch_by_id(self, setting_id: int) -> SettingRecord | None:
        """Get a setting record by ID."""
        rows = self.db.fetch_query_safe(
            "SELECT * FROM `settings` WHERE `id` = %s",
            (setting_id,),
        )
        if not rows:
            logger.warning(f"Setting record with ID {setting_id} not found")
            return None
        return self._row_to_record(rows[0])

    def fetch_by_key(self, key: str) -> SettingRecord | None:
        """Get a setting record by key."""
        rows = self.db.fetch_query_safe(
            "SELECT * FROM `settings` WHERE `key` = %s",
            (key,),
        )
        if not rows:
            return None
        return self._row_to_record(rows[0])

    def list(self) -> List[SettingRecord]:
        """Return all setting records."""
        rows = self.db.fetch_query_safe("SELECT * FROM `settings` ORDER BY `id` ASC")
        return [self._row_to_record(row) for row in rows]

    def add(
        self,
        key: str,
        title: str,
        value_type: str = "boolean",
        value: Any = None,
    ) -> SettingRecord:
        """Add a new setting record."""
        key = key.strip()
        title = title.strip()
        if not key:
            raise ValueError("Key is required")
        if not title:
            raise ValueError("Title is required")

        data = SettingRecord(
            id=0,  # Placeholder, will be auto-generated by DB
            key=key,
            title=title,
            value_type=value_type,
            value=value,
        )

        try:
            self.db.execute_query(
                """
                INSERT INTO `settings` (`key`, `title`, `value_type`, `value`)
                VALUES (%s, %s, %s, %s)
                """,
                (data.key, data.title, data.value_type, data.value),
            )
        except pymysql.err.IntegrityError:
            raise ValueError(f"Setting with key '{data.key}' already exists") from None

        record = self.fetch_by_key(data.key)
        if not record:
            raise RuntimeError(f"Failed to fetch newly created setting '{data.key}'")
        return record

    def update_value(self, setting_id: int, value: Any) -> SettingRecord:
        """Update a setting record."""
        record = self.fetch_by_id(setting_id)
        if not record:
            raise ValueError(f"Setting record with ID {setting_id} not found")

        record.value = value

        self.db.execute_query_safe(
            "UPDATE `settings` SET `value` = %s WHERE `id` = %s",
            (record.value, setting_id),
        )
        updated = self.fetch_by_id(setting_id)
        if not updated:
            raise RuntimeError(f"Failed to fetch updated setting with ID {setting_id}")
        return updated

    def delete(self, setting_id: int) -> SettingRecord:
        """Delete a setting record by ID."""
        record = self.fetch_by_id(setting_id)
        if not record:
            raise ValueError(f"Setting record with ID {setting_id} not found")

        self.db.execute_query_safe(
            "DELETE FROM `settings` WHERE `id` = %s",
            (setting_id,),
        )
        return record
