[pytest]
# Pytest configuration file
pythonpath = .
# Test discovery patterns
python_files = test*.py *Test.py Test*.py
python_classes = Test*
python_functions = test*

# Test paths
testpaths = tests

# Output options
addopts =
    -v
    --strict-markers
    --tb=short
    -m "not network"
    --durations=10
    ; --cov=src/main_app
    --cov-report=term-missing
    --cov-report=xml
    --cov-branch
    --maxfail=250
    --log-cli-level=ERROR

# Markers for organizing tests
markers =
    unit: marks tests as unit tests
    integration: marks integration tests
    network: marks tests that require network access (deselect with '-m "not network"')
filterwarnings =
    ignore::DeprecationWarning
    ignore::PendingDeprecationWarning
    ignore:coroutine 'AsyncMockMixin._execute_mock_call' was never awaited:RuntimeWarning
    ignore::ResourceWarning
    ignore:unclosed database <sqlite3.Connection:ResourceWarning
    ignore:unclosed database in <sqlite3.Connection object at
    ignore:Enable tracemalloc to get the object allocation traceback

# Coverage options
[coverage:run]
source = src
omit =
    */tests/*
    */test_*
    */__pycache__/*
    */venv/*

[coverage:report]
precision = 2
show_missing = True
skip_covered = False

; python -m cProfile -o profile_slow.prof -m pytest -m slow
; snakeviz profile_slow.prof
