"""Pages db services."""

from .in_process_service import (
    add_in_process,
    delete_in_process,
    delete_in_process_by_title_user_lang,
    get_in_process,
    get_in_process_by_title_user_lang,
    get_in_process_counts_by_user,
    is_in_process,
    list_in_process,
    list_in_process_by_lang,
    list_in_process_by_user,
    update_in_process,
)
from .leaderboard_service import (
    get_leaderboard_chart_data,
    get_months_of_pages_years,
    get_pages,
    get_pages_years,
    list_of_users_by_translations_count,
    top_lang_of_users,
)
from .missing_stats_service import (
    count_category_members,
    statics_by_category,
)
from .page_service import (
    add_page,
    add_translate_row_to_db,
    delete_page,
    find_exists_or_update_page,
    insert_page_target,
    list_pages,
    list_pages_by_lang_cat,
    update_page,
)
from .pages_users_to_main_service import (
    check_main_page_exists,
    get_user_page,
    list_pending,
)
from .results_2026_service import (
    exists_by_lang_and_category,
    missing_by_lang_and_category,
)
from .translate_type_service import (
    add_translate_type,
    can_translate_full,
    can_translate_lead,
    delete_translate_type,
    get_translate_type,
    get_translate_type_by_title,
    list_full_enabled_types,
    list_lead_enabled_types,
    list_new_titles,
    list_translate_types,
    update_translate_type,
)
from .user_page_service import (
    add_user_page,
    count_translated,
    delete_user_page,
    find_exists_or_update_user_page,
    get_by_id,
    insert_user_page_target,
    list_translated,
    list_user_pages,
    update_user_page,
)

__all__ = [
    "list_in_process",
    "list_in_process_by_user",
    "list_in_process_by_lang",
    "get_in_process",
    "get_in_process_by_title_user_lang",
    "add_in_process",
    "update_in_process",
    "delete_in_process",
    "delete_in_process_by_title_user_lang",
    "is_in_process",
    "get_in_process_counts_by_user",
    "get_pages_years",
    "get_months_of_pages_years",
    "list_of_users_by_translations_count",
    "get_pages",
    "top_lang_of_users",
    "get_leaderboard_chart_data",
    "count_category_members",
    "statics_by_category",
    "list_pages",
    "list_pages_by_lang_cat",
    "add_page",
    "update_page",
    "delete_page",
    "find_exists_or_update_page",
    "insert_page_target",
    "add_translate_row_to_db",
    "list_pending",
    "get_user_page",
    "check_main_page_exists",
    "delete_user_page",
    "missing_by_lang_and_category",
    "exists_by_lang_and_category",
    "list_translate_types",
    "list_new_titles",
    "list_lead_enabled_types",
    "list_full_enabled_types",
    "get_translate_type",
    "get_translate_type_by_title",
    "add_translate_type",
    "update_translate_type",
    "delete_translate_type",
    "can_translate_lead",
    "can_translate_full",
    "list_user_pages",
    "list_translated",
    "count_translated",
    "get_by_id",
    "add_user_page",
    "update_user_page",
    "find_exists_or_update_user_page",
    "insert_user_page_target",
]
